# Generated by Django 6.0.7 on 2026-07-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_created_by_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('successful', 'Successful'), ('unsuccessful', 'Unsuccessful')], default='successful', max_length=20),
        ),
    ]
