# Generated by Django 6.0.7 on 2026-07-30 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_category_options_remove_category_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
            ],
            options={
                'verbose_name': 'Sub Category',
                'verbose_name_plural': 'Sub Categories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.category',),
        ),
    ]
