# Generated by Django 6.0.7 on 2026-07-30 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_attribute_attributevalue'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='category',
            new_name='subcategory',
        ),
    ]
