# Generated by Django 6.0.7 on 2026-07-30 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_rename_category_attribute_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.product')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.attributevalue')),
            ],
            options={
                'unique_together': {('product', 'attribute', 'value')},
            },
        ),
    ]
