# Generated by Django 6.0.7 on 2026-08-07 07:49

import django.db.models.deletion
from django.db import migrations, models


def remove_duplicate_variant_attributes(apps, schema_editor):
    VariantAttribute = apps.get_model('store', 'VariantAttribute')
    seen = set()
    # Keep the first occurrence of each (variant, attribute) and delete any duplicates
    for va in VariantAttribute.objects.all().order_by('id'):
        key = (va.variant_id, va.attribute_id)
        if key in seen:
            va.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_drop_unused_admin_status_column'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_variant_attributes, reverse_code=migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='variantattribute',
            unique_together={('variant', 'attribute')},
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='store.productvariant')),
            ],
        ),
    ]
