# Generated by Django 6.0.7 on 2026-08-07 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_variantattribute_unique_together_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='start_date',
        ),
    ]
