# Generated by Django 6.0.7 on 2026-08-10 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_vendorsubscriptionplan_vendorsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsubscriptionplan',
            name='razorpay_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
