# Generated by Django 6.0.7 on 2026-08-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_vendorsubscriptionplan_razorpay_plan_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], default='monthly', max_length=20),
        ),
    ]
