# Generated by Django 6.0.7 on 2026-08-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_vendorsubscription_billing_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsubscriptionplan',
            name='duration_days',
            field=models.PositiveIntegerField(default=30, help_text='Duration of the subscription in days'),
        ),
        migrations.AddField(
            model_name='vendorsubscriptionplan',
            name='product_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum products. Empty means unlimited.', null=True),
        ),
    ]
