# Generated by Django 6.0.7 on 2026-08-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_vendorsubscriptionplan_duration_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorsubscriptionplan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
