# Generated by Django 6.0.7 on 2026-08-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_vendorsubscriptionplan_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorsubscriptionplan',
            old_name='razorpay_plan_id',
            new_name='razorpay_annual_plan_id',
        ),
        migrations.RemoveField(
            model_name='vendorsubscriptionplan',
            name='billing_cycle',
        ),
        migrations.RemoveField(
            model_name='vendorsubscriptionplan',
            name='price',
        ),
        migrations.AddField(
            model_name='vendorsubscriptionplan',
            name='annual_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorsubscriptionplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vendorsubscriptionplan',
            name='razorpay_monthly_plan_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
