# Generated by Django 6.0.7 on 2026-08-13 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductManufacturingDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_of_origin', models.CharField(max_length=100)),
                ('manufacturer_name', models.CharField(max_length=200)),
                ('manufacturer_address', models.TextField()),
                ('packer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('packer_address', models.TextField(blank=True, null=True)),
                ('importer_name', models.CharField(blank=True, max_length=200, null=True)),
                ('importer_address', models.TextField(blank=True, null=True)),
                ('manufacturing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manufacturing_details', to='store.product')),
            ],
        ),
    ]
