from django.urls import path
from . import views
from .views import CustomTokenObtainPairView
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    path('products/', views.get_products),
    path('products/<int:pk>/', views.get_product),
    path('products/<int:pk>', views.get_product),
    path('admin/products/', views.admin_products),
    path('products/create/', views.create_product),
    path('products/<int:pk>/update/', views.update_product),
    path('products/<int:pk>/delete/', views.delete_product),
    path('categories/', views.get_categories),
    path('admin/categories/', views.admin_categories),
    path('categories/create/', views.create_category),
    path('categories/<int:pk>/update/', views.update_category),
    path('categories/<int:pk>/delete/', views.delete_category),
    path('cart/', views.get_cart),
    path('cart/add/', views.add_to_cart),
    path('cart/remove/<int:pk>/', views.remove_from_cart),
    path('cart/update/<int:pk>/', views.update_cart),
    path('checkout/', views.checkout),
    path('checkoutRaz/', views.checkout_razorpay, name='checkout-razorpay'),
    path('checkoutRaz/verify/', views.checkout_razorpay_verify, name='checkout-razorpay-verify'),
    path('orders/mine/', views.my_orders),
    path('orders/mine/<int:pk>/', views.my_order_detail),
    path('orders/', views.get_orders),
    path('orders/<int:pk>/', views.get_order_detail),
    path('ratings/', views.create_rating),
    path('ratings/mine/', views.my_ratings),
    path('products/<int:pk>/ratings/', views.product_ratings),
    path('admin/ratings/', views.admin_product_ratings),
    path('dashboard/stats/', views.get_dashboard_stats),
    path('register/', views.register),
    path('login/', CustomTokenObtainPairView.as_view()),
    path('forgot-password/', views.forgot_password),
    path('reset-password/', views.reset_password),
    path('refresh/', TokenRefreshView.as_view()),
    path('profile/', views.get_profile),
    path('profile/update/', views.update_profile),
]